### ISSUE TITLE
Problem with Single View

### ISSUE THREAD

**Issue by leofisc** [featdd/dpn_glossary#121]
Everything seems to work with the Plugin, but when i click on a parsed term, i will come to the Single-View-site which shows me an exception: 

_the action "show" (controller "Term") is not allowed by this plugin. Please check TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin() in your ext_localconf.php_

**Comment by featdd** [comment]
I need more details, did you configure your plugin properly?

**Comment by ichbinvinh** [comment]
Hallo Daniel,

i have upgraded my website to new version Typo3 9.5.1 and used dpn_glossary 3.01. Now i have the same problem as Leofisc does. Because you have removed "seperat detailpage plugin" i have to add new this manually.
Could you give me some suggestion? thank you.

**tt_content.php:**

` \TYPO3\CMS\Extbase\Utility\ExtensionUtility::registerPlugin(
           'dpn_glossary',
            'Glossarydetail',
            'LLL:EXT:dpn_glossary/Resources/Private/Language/locallang.xlf:tx_dpnglossary.wizard_detail_title'
        );`

**ext_localconf.php:**

`\TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin(
            'Featdd.' . $extKey,
            'Glossarydetail',
            [
                'Term' => 'show',
            ],
            // non-cacheable actions
            [
                'Term' => '',
            ]
        );`

**List.html**

` <f:if condition="{listmode} == 'normal'">

      <div class="uk-glossary-list-mode">
        <dl>
          <f:for each="{terms}" as="term">
            <dt>
              <f:link.action pageUid="{detailPage}" action="show" arguments="{term: term}">{term.name}</f:link.action>
            </dt>
            <dd>{term.tooltiptext}</dd>
          </f:for>
        </dl>
      </div>

    </f:if>`

`TermController.php bleibt:`

` /**
     * @param \Featdd\DpnGlossary\Domain\Model\Term $term
     * @param integer $pageUid
     */
    public function showAction(Term $term = null, $pageUid = null): void
    {
        if ('pagination' === $this->settings['listmode']) {
            $this->view->assign(
                'paginateLink',
                PaginateController::paginationArguments(
                    $term->getName(),
                    $this->settings['pagination']['characters']
                )
            );
        }

        if ((int) $this->settings['detailPage'] !== $pageUid) {
            $this->view->assign('pageUid', $pageUid);
        }

        $this->view->assign('term', $term);
    }`

**Comment by featdd** [comment]
Hi @ichbinvinh,

The seperate detail plugin has been a relict from realurl times, due to the ability to configure proper looking urls.

This has been solved with the new routing in 9.5 and I took the chance to get rid of the detail plugin with a refactoring and a new major release.

The migration information should've gave you the information that you have to migrate this yourself.
You'll have to disable your detailpage and change the list plugin to the new main plugin, which you can configure like explained in the documentation.

**Comment by ichbinvinh** [comment]
thank you, now it works!
