### ISSUE TITLE
worse performance with parsing enabled

### ISSUE THREAD

**Issue by christiana83** [featdd/dpn_glossary#150]
hello dev- team,

while using the settings 
```
useCachingFramework = 1 
disableParser = 0

```
the website perfomance slows down extremly. any ideas how we could fix that issue?

thank you in advance!

**Comment by featdd** [comment]
I didn't have any issues of this kind.

But there are possibilities to optimize performance, the hook still instanciates the service with the terms and checks if the parser is disabled when the _pageParser_ method is called.

I will refactor this for the next update.

Greetings
Daniel

**Comment by christiana83** [comment]
Thanks for your response! 

Greetings, Christiana

**Comment by featdd** [comment]
Ah I just saw that I misread your issue, the problem is the hook, which also is enabled on cached sites due to an issue in the core.

When pages are cached the page will be generated in a seperated call which would bypass the non cached hook. I have to re test this if this is still an issue in v8 and v9.

Greetings
Daniel

**Comment by featdd** [comment]
Hi @christiana83,

could you do me a favour and check if this (cca69d99bdff53b3b454b245c3d8fb9687b4933c) works for you?

I tested it on the latest v9.5.14, only using the hook for the cached output. In my test the hook only executed when logged in to the backend, otherwise the cached content with the parsed terms was fetched. But I had issues with this in the past, so I need some feedback before I push this for the next update.

Greetings
Daniel

**Comment by christiana83** [comment]
Hi Daniel,

I am very happy that you are helping us. I will test it and give you feedback.

Greetings, Christiana

**Comment by featdd** [comment]
Hi @christiana83, 

always glad if I can help, did the experimental change worked out for you?

Greeting
Daniel

**Comment by christiana83** [comment]
Hi Daniel,

now cached pages are loaded very quickly, including a glossary! 
Before first parsing it is still slowly. But in when pages are in cache, it's performant.

Thank you for your help!

Greetings, Christiana

**Comment by featdd** [comment]
Hi @christiana83,

thanks for your feedback, I will make some additional test this and properly merge this for the next update.

I'll leave the issue open until its in master.

Greetings
Daniel

**Comment by featdd** [comment]
solved in 7650586ddb81737ff31d26b26733e8aaef70fcfe
