### ISSUE TITLE
Umlauts upper and lower case is not distinguished correctly

### ISSUE THREAD

**Issue by Daniel-Siteway** [featdd/dpn_glossary#189]
As soon as umlauts appear in the first position of the term, they are not recognized correctly by the pharser and accordingly the word is not linked. 

In my case:

If the term "Öffentlicher Dienst" is entered, it is recognized in the frontend only with a capital Ö. In this case, "öffentlicher Dienst" is not recognized and case sensitivity is also disabled in the term.

If I now create the term with "öffentlicher Dienst", the term is also recognized, but no longer the capitalized variant "Öffentlicher Dienst".

Currently the version 4.1.0 is used in a TYPO3 11 system.

![Bildschirmfoto 2023-02-28 um 10 34 06](https://user-images.githubusercontent.com/69299179/221812259-692f8928-588e-418b-b6e5-fd0ffd57dbe2.png)

![Bildschirmfoto 2023-02-28 um 10 34 37](https://user-images.githubusercontent.com/69299179/221812277-cc6af271-e53f-43d8-bfc2-55613a39a8d3.png)

**Comment by featdd** [comment]
Hi @Daniel-Siteway,

thanks for the hint to this issue.

The problem here is that the regex can't differ the character case of the umlauts, even though it is explicitly told to do so.
This probably goes down to PHP and character encoding itself handling umlauts like special symbols. (no guarante for this explanation)

Nevertheless I could build a workaround making the case insensitivity work by manipulating the regex a bit.

see: 4470151f4d14e299b518f1f3ba7d3eba9cc1660e

Please let me hear your feedback is this worked out for you.

Greetings
Daniel

**Comment by Daniel-Siteway** [comment]
@featdd 

thanks for this fix.

Works as expected :)

**Comment by braukma** [comment]
Hi Daniel,
I am facing a similar problem with PHP 7.4, Typo3 11.5 and dpn_glossary 4.2.0.
Can't use 5.x due to PHP issues with another extension.

In My case, Upper case Umlauts are fine (first letter) like "Ökologisch" but any lower case Umlaut within a word like "möglich" ends up like "möglichö". The ö overwites the tailing space.

Tried to use the patch, but failed. Maybe due to my inexperiance in working with git, but maybe it's another issue.

Jürgen

**Comment by featdd** [comment]
Hi @braukma,

the latest version 5.0.4 still works fine with TYPO3 11.5, did you extend the extension or something else?
Unfortionately I can't give you support for problems not related to the extension. (maybe have a look in the TYPO3 slack for general help)

Greetings
Daniel

**Comment by braukma** [comment]
Hi Daniel,

well:
Die folgenden Fehler wurden gefunden als versucht wurde, "dpn_glossary" zu installieren:

    **Your PHP version is lower than necessary. You need at least PHP version 8.0.0**

I am on PHP 7.4 and unfortunately fail on that requirement. Thus, Version 4.2.0

But havn't tried PHP 8.0 yet. Faced other issues with PHP 8.1 and another extension.

Jürgen

**Comment by featdd** [comment]
Hi @braukma,

ah okay, unfortunately I'm not planning to do any backwards compatibility.
You could still try to apply the patch manually.

Greetings
Daniel
