### ISSUE TITLE
Compatibility Issue with TYPO3 v11.5 and PHP 7.4.x

### ISSUE THREAD

**Issue by branosvk** [featdd/dpn_glossary#212]
Hello,

I hope this message finds you well. I am currently using TYPO3 version 11.5.33 with PHP 7.4.20. As per TYPO3's system requirements (https://get.typo3.org/version/11#system-requirements), the supported PHP versions range from 7.4.1 to 8.3.99.

I've noticed that on the TYPO3 Extension Repository (https://extensions.typo3.org/extension/dpn_glossary), featdd/dpn-glossary is listed as compatible with TYPO3 versions 11.5.0 to 12.4.99.

Given that my environment runs PHP 7.4.20, and I'm unable to update to a higher PHP version due to dependencies of other extensions, I am facing compatibility issues with featdd/dpn-glossary, which has a requirement of PHP >= 8.0.

I am reaching out to inquire whether it is absolutely necessary for featdd/dpn-glossary to have a PHP version dependency of >= 8.0. If possible, could this requirement be adjusted to ensure compatibility with TYPO3 v11.5 instances running on servers with PHP versions between 7.4.1 and 8.3.99?

Thank you for your attention to this matter. I appreciate your time and assistance.

Best regards,
Brano Kotik

**Comment by featdd** [comment]
Hi @branosvk,

this would require me to do some code refactoring as there are things available only since PHP 8.0.
While TYPO3 itself still supports it, [PHP 7.4 is officially dead since end of 2022](https://www.php.net/supported-versions.php).

So unfortunately I can't officially go backwards here, but I know the strugglge of upgrading systems and dealing with locked PHP versions and so on.
You're still able to download the extension and make these backwards compatible changes yourself.
I thinks it's mainly try catch blocks still needing a variable in 7.4 and so on.

Greetings
Daniel
