### ISSUE TITLE
More than one synonym not parsed

### ISSUE THREAD

**Issue by kayATcu** [featdd/dpn_glossary#213]
Hi,

we have typo3 version 12 and use this extension in the newest version.

But if i have more than one "synonyms", it will underline only the first synonym in frontend and not the others.
![2024-02-29_15-33](https://github.com/featdd/dpn_glossary/assets/107566356/f4c9588e-f851-46fe-830a-68fd4b14727b)

Best regards,
Kay

**Comment by featdd** [comment]
Hi @kayATcu,

have you set a max replacement limit?

Greetings
Daniel

**Comment by kayATcu** [comment]
@featdd no. Everything is default.
![grafik](https://github.com/featdd/dpn_glossary/assets/107566356/847fa403-88a1-4687-9734-40404e102067)
![2024-02-29_16-18](https://github.com/featdd/dpn_glossary/assets/107566356/d7689b52-70cd-4692-a8e8-5027466c6a57)
![2024-02-29_16-18_1](https://github.com/featdd/dpn_glossary/assets/107566356/4923ebbe-3b9f-4eb5-9a55-32c35d549805)

**Comment by kayATcu** [comment]
@featdd i think i found the problem....
--- vendor/featdd/dpn-glossary/Classes/Service/ParserService.php	2024-02-18 21:15:02.000000000 +0100
+++ patches/ParserService-new.php	2024-03-01 11:10:00.536245476 +0100
@@ -405,8 +405,9 @@
 
             if ($isParseSynonyms) {
                 $synonymTermObject = clone $termObject;
+                $allSynonyms = $termObject->getSynonyms()->toArray();
                 /** @var \Featdd\DpnGlossary\Domain\Model\Synonym $synonym */
-                foreach ($termObject->getSynonyms() as $synonym) {
+                foreach ($allSynonyms as $synonym) {
                     $synonymTermObject->{
                     ($this->settings['useTermForSynonymParsingDataWrap'] ?? false)
                         ? 'setParsingName'


Greetings,
Kay

**Comment by featdd** [comment]
Hi @kayATcu,

I couldn't believe my eyes first when I reproduced this and struggled to find an explanation, this is really a fine piece of an edge case. 😅 

The issue was that I build a nested iteration over the synonym ObjectStorage, because inside the iteration the parser calls the "__toArray()" function of the term, wich also iterates over the ObjectStorage.
This is resulting in an array reset inside the ObjectStorage's internal array, messing up the overlaying iteration and so on...

Anyway here's the fix: 86a5767db2d209d4a64868a31d3d4f9ae5356936

I will also prepare an update for the TER.

Greetings
Daniel
