### ISSUE TITLE
[QUESTION] WrapperService

### ISSUE THREAD

**Issue by p2media** [featdd/dpn_glossary#43]
Can you explain what exactly the `WrapperService` does?

If I include your provided static TS-Template and request any page where the plug-in is not in the content, I get the following error:
`PHP Fatal error:  Using $this when not in object context in /typo3/typo3conf/ext/dpn_glossary/Classes/Service/WrapperService.php on line 302`

I resolved the issue by disabling the Tags:
```
plugin.tx_dpnglossary.settings.parsingTags =
```

FYI:
TYPO 6.2.14
dpn_glossary 2.3.4 (GitHub Version)
PHP 5.3.29 _(I know... but there is some very old code :/)_

P.S. On the development system with the same configuration (without the dirty fix) everything works fine

**Comment by featdd** [comment]
the error is caused by your low php version. in the em_conf the php minimum is set to 5.4!
It's because I have to use a callback function.
The parser filters the parsingTags with a DomDocument and with a regex I parse the nodes html for tags for which I use the callback.

See in WrapperService.php line: 298-308
